LABEL_FOR_CODING_SEQUENCES = 1
LABEL_FOR_NON_CODING_SEQUENCES = 0
CODING_SEQ_DATA = 'cds_from_genomic.fna'
CANDIDA_A_GENOME_FASTA='GCA_000182965.3_ASM18296v3_genomic.fna'
CODING_SEQUENCES_CSV = 'coding_sequences.csv'